### ISSUE TITLE
2 unnecessary files?

### ISSUE THREAD

**Issue by cDenius** [cirKITers/quantum-framework-runtime-eval#5]
Is there any reason why [qiskit-test_duration_multiprocessing.py](https://github.com/cirKITers/quantum-framework-runtime-eval/blob/341da17bbd63a77149c88074731ad49bac0f5932/qiskit-test_duration_multiprocessing.py) and [qiskit-test_expval.py](https://github.com/cirKITers/quantum-framework-runtime-eval/blob/341da17bbd63a77149c88074731ad49bac0f5932/qiskit-test_expval.py) are still part of the repo? It seems to me that they have been replaced (and improved) with [test_duration.py](https://github.com/cirKITers/quantum-framework-runtime-eval/blob/341da17bbd63a77149c88074731ad49bac0f5932/test_duration.py).

**Comment by stroblme** [comment]
yes, you're right, they are leftovers and can be deleted
